# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vI4IKQJAGJjt0LoNgNCE9CBLNenpL6v
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# ============================================================
# Preprocessing Function
# ============================================================

def preprocess_dataset(file_path, target_column):


    # Load Dataset
    df = pd.read_csv(file_path)

    print("Dataset Loaded Successfully")
    print("Shape :", df.shape)


    # Data Cleaning

    print("\nRemoving duplicate records...")
    df = df.drop_duplicates()

    print("Removing missing values...")
    df = df.dropna()


# Replace values: 1 if greater than or equal to 4, otherwise 0
df.loc[df['vt_detection'] < 4, 'vt_detection'] = 0 # Set all to 0
df.loc[df['vt_detection'] >= 4, 'vt_detection'] = 1  # Set to 1 where condition is met
print(df)
    # Separate Features and Target
    leakage_columns = []

if "vt_detection" in df.columns:
    leakage_columns.append("vt_detection")

if "Class" in df.columns:
    leakage_columns.append("Class")

# Keep only the actual target column
if target_column in leakage_columns:
    leakage_columns.remove(target_column)

X = df.drop(columns=leakage_columns + [target_column], errors="ignore")
y = df[target_column]



    # Label Encoding

    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(y)

    # Encode categorical input features

    for column in X.select_dtypes(include=['object']).columns:

        encoder = LabelEncoder()
        X[column] = encoder.fit_transform(X[column])


    # Feature Normalization

    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    # Train (70%) and Temporary (30%)
    X_train, X_temp, y_train, y_temp = train_test_split(

        X,
        y,
        test_size=0.30,
        random_state=42,
        stratify=y

    )


    # Validation (15%) and Testing (15%)
       X_valid, X_test, y_valid, y_test = train_test_split(
        X_temp,
        y_temp,
        test_size=0.50,
        random_state=42,
        stratify=y_temp)


    # Save Processed Datasets
    train_data = pd.DataFrame(X_train)
    train_data[target_column] = y_train

    valid_data = pd.DataFrame(X_valid)
    valid_data[target_column] = y_valid

    test_data = pd.DataFrame(X_test)
    test_data[target_column] = y_test

    train_file = "train_data.csv"
    valid_file = "validation_data.csv"
    test_file = "test_data.csv"

    train_data.to_csv(train_file, index=False)
    valid_data.to_csv(valid_file, index=False)
    test_data.to_csv(test_file, index=False)

    print("\nDataset Split Completed Successfully")
    print("----------------------------------------")
    print("Training Samples   :", len(train_data))
    print("Validation Samples :", len(valid_data))
    print("Testing Samples    :", len(test_data))

    return train_file, valid_file, test_file